### ISSUE TITLE
Get Issue when run Docker Run command

### ISSUE THREAD

**Issue by jaiminrockersinfo** [codefresh-contrib/php-composer-sample-app#1]
`Unable to find image 'php-sample-app:latest' locally
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: pull access denied for php-sample-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.`

**Comment by kostis-codefresh** [comment]
Hello. You need to build the image first. 

```
docker build . -t php-sample-app
```
